"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================
# 🔒 SECURITY SETTINGS
# =============================================================

# Never keep DEBUG=True in production.
DEBUG = False

# Keep your secret key safe. Use environment variables for production.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'insecure-key-for-dev')

# Define allowed hosts explicitly to prevent Host header attacks.
ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com', '127.0.0.1', 'localhost']

# Enforce HTTPS — redirect all HTTP traffic to HTTPS
SECURE_SSL_REDIRECT = True

# HTTP Strict Transport Security (HSTS)
# Instructs browsers to always use HTTPS for your site
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Browser-side protections
SECURE_BROWSER_XSS_FILTER = True                 # Enables browser XSS filtering
SECURE_CONTENT_TYPE_NOSNIFF = True               # Prevents MIME-type sniffing
X_FRAME_OPTIONS = 'DENY'                         # Protects against clickjacking
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Safer referer headers

# Ensure cookies are only sent via HTTPS
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# If behind a reverse proxy (like Nginx with SSL)
# This tells Django to trust the proxy’s HTTPS header
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# =============================================================
# APPLICATION CONFIGURATION
# =============================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# =============================================================
# DATABASE CONFIGURATION
# =============================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# =============================================================
# AUTHENTICATION & REDIRECTS
# =============================================================

LOGIN_REDIRECT_URL = 'list_books'   # Redirect to books list after login
LOGOUT_REDIRECT_URL = 'login'       # Redirect to login page after logout
LOGIN_URL = 'login'                 # URL to redirect to when login is required

AUTH_USER_MODEL = 'bookshelf.CustomUser'


# =============================================================
# PASSWORD VALIDATION
# =============================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =============================================================
# INTERNATIONALIZATION
# =============================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# =============================================================
# STATIC FILES
# =============================================================

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production use with collectstatic


# =============================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# =============================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
